# SPDX-License-Identifier: GPL-2.0

dtbo-y += exynos9825-f62_swa_ins_00.dtbo
dtbo-y += exynos9825-f62_swa_ins_01.dtbo
dtbo-y += exynos9825-f62_swa_ins_02.dtbo
dtbo-y += exynos9825-f62_swa_ins_03.dtbo

always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
